title: CS184 Final Project
description: CS184 Final Project Webpage
theme: just-the-docs

url: https://cal-cs184-student.github.io
baseurl: /project-webpages-acdj

include:
  - mc_videos

keep_files:
  - mc_videos
